### ISSUE TITLE
The 5.0 update

### ISSUE THREAD

**Issue by HSGamer** [BetterGUI-MC/BetterGUI#159]
# General Changelog
* update HSCore to 2.0
* rewrite the menu system to use HSCore-bukkit-gui

**Comment by HSGamer** [comment]
# Proposed Changelog
## Name changes
* `Item Properties` to `Item Modifier`
* `Icon` to `Button`
## New
### Predicate Button
* **Description**: A combination of available `view-requirement` and `click-requirement`, and a new **fallback-button** (Used when the `view-requirement` is not met). Used to replace `view-requirement` and `click-requirement` of some buttons and allow for more complicated structures of buttons.
* **Usage** (draft):
```yaml
<button-name>:
  type: predicate
  view-requirement:
    <requirement1>
    <requirement2>
    <requirement3>
    ...
  click-requirement:
    <requirement1>
    <requirement2>
    <requirement3>
    ...
  button:
    <property1>
    <property2>
    <property3>
    ...
  fallback-button:
    <property1>
    <property2>
    <property3>
    ...
```
## Remove
* `view-requirement` and `click-requirement` of `Simple Button` and `Animated Button`
## Change
* Switch the GUI library from `FastInv` to `HSCore-bukkit-gui`
* Rework the `Menu & Button` system to adapt for the new library
* Rework the `Item Modifier` system to use the system from `HSCore-bukkit-item`

**Comment by HSGamer** [comment]
# TODO
- [ ] Commands
  - [ ] AddonDownloaderCommand
  - [ ] GetAddonsCommand
  - [ ] MainCommand
  - [ ] OpenCommand
  - [ ] ReloadCommand
- [ ] Command Builder
  - [ ] BackCommand
  - [ ] BroadcastCommand
  - [ ] CloseMenuCommand
  - [ ] ConditionCommand
  - [ ] ConsoleCommand
  - [ ] DelayCommand
  - [ ] MusicCommand
  - [ ] OpCommand
  - [ ] OpenMenuCommand
  - [ ] PermissionCommand
  - [ ] PlayerCommand
  - [ ] RawSoundCommand
  - [ ] SoundCommand
  - [ ] TellCommand
  - [ ] UpdateMenuCommand
- [ ] Menu Builder
  - [ ] SimpleMenu
  - [ ] ArgsMenu
  - [ ] DummyMenu
- [ ] Button Builder
  - [ ] Simple Button
  - [ ] Animated Button
  - [ ] List Button
  - [ ] Empty Button
  - [ ] Dummy Button
  - [ ] Predicate Button
- [ ] Requirement Builder
  - [ ] ConditionRequirement
  - [ ] CooldownRequirement
  - [ ] ExpLevelRequirement
  - [ ] PermissionRequirement
- [ ] Global Variable Manager
- [ ] Item Modifier Builder
  - [ ] name
  - [ ] lore
  - [ ] amount
  - [ ] material
  - [ ] enchantment
  - [ ] item flags
  - [ ] durability
  - [ ] skull
  - [ ] potion
- [ ] Property Builder
  - [ ] Icon Properties
    - [ ] close-on-click
    - [ ] command
  - [ ] Menu Properties
    - [ ] open-action
    - [ ] close-action
    - [ ] inventory-type
    - [ ] rows
    - [ ] auto-refresh
    - [ ] name
    - [ ] view-requirement
    - [ ] close-requirement
- [ ] Addon Manager
  - [ ] Additional Settings
    - [ ] authors
    - [ ] description
    - [ ] depend
    - [ ] soft-depend
    - [ ] plugin-depend

**Comment by HSGamer** [comment]
# Addon Update
* [x] ComplexTextSender (1.1)
* [x] World-And-Region (1.2)
* [ ] OptEcoBridge
* [ ] BungeeLink
* [ ] ItemListener
* [ ] TargetMenu
* [ ] ASCII-Placeholders
* [ ] AdvancedCooldown
* [ ] AnvilGUI
* [ ] CosmeticsTweak
* [ ] NPC-Opener
* [ ] SwitchIcon
* [ ] ItemGotcha
* [ ] TokenManagerBridge
* [ ] VaultBridge
* [ ] PlayerPointsBridge
* [ ] BlockListener
